# Generated by Django 4.2.3 on 2023-10-21 10:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=15, verbose_name='cassaga kirish uchun password ')),
                ('Balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='umimiy cassada bor summa')),
            ],
            options={
                'verbose_name': 'Cassa',
                'verbose_name_plural': 'Cassa',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('employee_status', models.IntegerField(choices=[(1, 'doktor'), (2, 'admin'), (3, 'boshqaruvchi')])),
                ('description', models.TextField(verbose_name='batafsil malumot')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='ish tajribasi')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ish haqi')),
                ('age', models.IntegerField(verbose_name='yoshi')),
                ('specialty', models.CharField(max_length=30, verbose_name='mutaxasisligi')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(verbose_name="to'liq malumot ")),
                ('employee_number', models.IntegerField(default=0, verbose_name='ishchilar soni')),
                ('number_of_recovered_orpatient', models.IntegerField(default=0, verbose_name='shifo topgan bemorlar soni')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='bemorning yaratilgan vaqti')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('photo', models.ImageField(null=True, upload_to='patient_photos/', verbose_name='patient photo')),
                ('gender', models.IntegerField(choices=[(1, 'Famele'), (2, 'Male')], verbose_name="bemorning' jinsi")),
                ('diagnos', models.CharField(max_length=30)),
                ('day', models.IntegerField(blank=True, null=True, verbose_name="bemorning' qancha kun dovolanishi")),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name="bemornig' doktori")),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="foyda '+'  summalar")),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="chiqim  '-'   summalar")),
                ('description', models.TextField(verbose_name="to'liq malumot")),
                ('date', models.DateField(verbose_name='hisobot chiqarilgan kun')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Report',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name="bo'lim nomi")),
                ('descriptioon', models.TextField(verbose_name="to'liq malumot")),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Xona Raqami')),
                ('is_booked', models.BooleanField(default=False)),
                ('room_capacity', models.IntegerField(verbose_name="xona sig'imi")),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Forpatient'), (2, 'for employee')])),
                ('category', models.IntegerField(choices=[(1, 'Lux'), (2, 'Econom'), (3, 'Operatsiya')])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.section', verbose_name='bolim xonasi ')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField(verbose_name='navbat raqami')),
                ('description', models.TextField(verbose_name="to'liq malumot ")),
                ('created_at', models.TimeField(auto_now=True, verbose_name='navbat yaratilgan vaqti ')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name="bemorning' doktori")),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queue',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="umumiy to'lov summa")),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name=" to'lov yaratilgan vaqti ")),
                ('code', models.CharField(max_length=20, unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.patient')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room', verbose_name="bemornig' xonasi"),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_time', models.TimeField(verbose_name='operatsiya qancha dovom etish vaqti ')),
                ('operation_time', models.DateTimeField(verbose_name='operatsa kuni va vaqti')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='operatsa summasi')),
                ('doctors', models.ManyToManyField(to='main.employee', verbose_name="bemroning' doktorlari")),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.patient', verbose_name='bemor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.room', verbose_name='operatsa xonasi')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operation',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room', verbose_name='xona'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('day', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Davomat uchun doktorni shaxsi ')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('adress', models.CharField(max_length=50, verbose_name='manzil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
