# Generated by Django 4.2.3 on 2023-10-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_status',
            new_name='status',
        ),
    ]
