# Generated by Django 4.2.3 on 2023-10-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='created_at',
            field=models.TimeField(auto_now=True, verbose_name='navbat yaratilgan vaqti '),
        ),
    ]
