# Generated by Django 4.2.3 on 2023-10-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_queue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(null=True, upload_to='patient_photos/', verbose_name='patient photo'),
        ),
    ]
