# Generated by Django 4.2.3 on 2023-10-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_patient_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateField(auto_created=True, verbose_name='bemorning yaratilgan vaqti'),
        ),
    ]
